export const CHANGELOG = [
  {
    version: "2.1.27",
    date: "2026-07-15",
    changes: [
      "Versión clickable: muestra el changelog completo en un modal",
    ],
  },
  {
    version: "2.1.26",
    date: "2026-07-15",
    changes: [
      "Traducciones reales para a11y/music/print/sectionOrder/langSwitcher en fr/de/pt/it/nl",
      "Mensajes de invitación en fr/de/pt en la sección Compartir",
      "25 keys faltantes añadidas a los 83 locales",
      "manualChunks para firebase y leaflet en vite.config.js",
      "Import estático de getDoc en PanelTab.jsx",
      "Verificado TTL de sessionExpiresAt (24h, controlado por Firestore rules)",
    ],
  },
  {
    version: "2.1.25",
    date: "2026-07-15",
    changes: [
      "Corregidas dependencias de useMemo, exportación y chunking en cascadeDelete",
      "Extraído useToast a hook propio, limpiados exports no usados",
    ],
  },
  {
    version: "2.1.22–24",
    date: "2026-07-13",
    changes: [
      "i18n: carga dinámica por idioma, chunk principal -87% (3.5 MB → 465 KB)",
      "Accesibilidad: contraste en 4 temas, teclado en galería, aria-live",
      "i18n: 61 keys muertas eliminadas de 84 locales (2254 eliminaciones)",
      "61 keys de traducción completadas en locales parciales",
    ],
  },
  {
    version: "2.1.18–21",
    date: "2026-07-12",
    changes: [
      "Auditoría: resueltos 9 críticos, 12 altos, 22 medios, 4 bajos",
      "TTL de sesión: sessionExpiresAt en Firestore rules + client (24h)",
      "CSP font-src, frame-ancestors, getFirestore corregidos",
      "Componentización: ThemePicker, GalleryManager, WeddingMap",
      "Galería con thumbnails 5rem, carrusel 3s, contenedor 56rem",
      "Panel admin full-width/height unificado",
    ],
  },
  {
    version: "2.1.13–17",
    date: "2026-07-11",
    changes: [
      "i18n: 50+ keys nuevas en 84 idiomas, cadenas hardcodeadas eliminadas",
      "Panel datos superadmin: export/eliminación individual y masiva",
      "Modal legal más ancho y sin scroll horizontal",
      "Fix line-height accesibilidad: unitless en vez de rem",
      "Galería con miniaturas en tiempo real, límite 10 imágenes",
      "Carrusel automático con descripciones editables y contador",
    ],
  },
  {
    version: "2.1.10–12",
    date: "2026-07-10",
    changes: [
      "Toast con barra de progreso real en subida de imágenes",
      "Cifrado de imágenes: chunked base64 evita overflow",
      "Regla Firestore para subcolección gallery",
      "Fade elegante en galería al cambiar de imagen",
    ],
  },
  {
    version: "2.1.5–9",
    date: "2026-07-09",
    changes: [
      "Refactor: useStoryNavigation, JSDoc, CSS duplicado eliminado",
      "Tests: useStoryNavigation, crypto, tokens, storage",
      "Imágenes adaptables al contenedor sin recorte fijo",
    ],
  },
  {
    version: "2.1.0–4",
    date: "2026-07-08",
    changes: [
      "Reproductor música con glassmorphism y scrubber",
      "Contador regresivo con años/meses/semanas/días",
      "Etiquetas alergias: Gluten, Lactosa, Frutos Secos, Mariscos",
      "Panel accesibilidad: 8 opciones, OpenDyslexic, alto contraste",
      "Footer con legal, idioma, accesibilidad y versión",
      "84 idiomas i18n con selector agrupado por región",
      "Modal legal con toggle animado, accesible globalmente",
      "Fix XSS en SetupForm, CSP reforzado",
    ],
  },
  {
    version: "2.0.1",
    date: "2026-07-07",
    changes: [
      "Sesiones migradas a activeSession en Firestore",
      "Reproductor música sticky con vinilo y controles",
      "Página impresión /print con componentes reales",
      "Compliance GDPR: Art. 30, CCPA, LGPD, PIPEDA, POPIA",
      "Cookie consent con configuración granular",
      "Superadmin: dashboard, invitaciones, tokens, compliance",
      "Imágenes cifradas AES-256-GCM en Firestore",
      "67 temas visuales con previsualización en vivo",
      "RSVP grupal con menú, alergias y restricciones",
      "Autoguardado con debounce 2s",
      "Galería con carrusel y navegación por teclado",
      "Mapa Leaflet con coordenadas automáticas",
      "Landing page con creación de invitación",
      "Panel admin: dashboard, edición, asistencia, compartir",
      "Sistema de sesión con renovación automática",
    ],
  },
];
