export const CHANGELOG = [
  {
    version: "2.48.0",
    date: "2026-08-05",
    changes: [
      "FEAT: las secciones sin contenido se ocultan en la invitación aunque estén en el orden de secciones (sectionHasContent en section-utils): detalle sin fecha/lugar, info sin horario/vestimenta/política, historia vacía, regalos sin texto/IBAN, alojamiento sin URL, transporte desactivado y galería sin imágenes",
      "FEAT: el menú no se muestra en el RSVP si no hay platos configurados (ya no aparecía con hasStructuredMenu/menuTextoDishes vacíos); se confirma que el menú no aparece en ninguna otra sección",
      "FEAT: al guardar, las secciones habilitadas sin contenido se desactivan automáticamente (se añaden a hiddenSections) y se muestra un mensaje informativo (errors.sectionsDeactivated) indicando cuáles",
      "CALIDAD: aislamiento de tests de ConfigContext (reseteo de mockSafeGetItem y sesión entre tests)",
    ],
  },
  {
    version: "2.47.1",
    date: "2026-08-05",
    changes: [
      "I18N: título de la sección 'Sobre los invitados' — 'Horario de la celebración' pasa a 'Itinerario' (es) / 'Itinerary' (en)",
    ],
  },
  {
    version: "2.47.0",
    date: "2026-08-05",
    changes: [
      "FEAT: modo de visualización de los mapas de Google — cada área con iframe (mapa de la boda, salidas de transporte y alojamiento) tiene su propio dropdown en el setup: mostrar el iframe completo (por defecto), mostrar solo el nombre de la ubicación u ocultar el mapa",
      "FEAT: nuevos campos detailsMapMode / transportMapMode / accommodationMapMode (valores iframe|name|hidden) en el esquema, normalize (whitelist con default iframe), codec y reglas de Firestore",
    ],
  },
  {
    version: "2.46.2",
    date: "2026-08-05",
    changes: [
      "FIX: subida de imágenes — se comprime aún más (máx 1920px, target 450KB crudos => cifrado ~600KB, con margen amplio bajo el límite de 1MB) para que el canal de Firestore no falle con payloads grandes",
      "FIX: reintentos en las escrituras de imagen (saveConfigImage/addGalleryImage) ante errores transitorios de red (unavailable/deadline-exceeded) — un blip de conexión ya no pierde la subida",
    ],
  },
  {
    version: "2.46.1",
    date: "2026-08-05",
    changes: [
      "FIX: subida de imágenes rota por el límite de 1MB de Firestore — el target de alta calidad se media en bytes crudos (length*3/4) pero el campo `data` guarda el base64 CIFRADO (~1.33x), que superaba 1MB y Firestore rechazaba (invalid-argument). El target baja a 700KB crudos (data URL ≤ ~933KB, cifrado ≤ ~933KB) y se añade una guarda de seguridad (MAX_ENCRYPTED_BYTES=1MB) en uploadImage y saveConfigImage para lanzar un error amigable en vez del fallo de Firestore",
    ],
  },
  {
    version: "2.46.0",
    date: "2026-08-05",
    changes: [
      "FEAT: calidad de imagen mejorada — la foto de novios, el fondo personalizado y la galería ahora se comprimen en alta calidad (máx 2400px y target ~700KB en vez de 1600px/300KB), aprovechando el límite de 1MB de las subcolecciones configImages/gallery",
      "PERF: compressImage y compressImageTransparent aceptan maxDimension/targetBytes; uploadImage comprime en alta calidad por defecto (la galería se beneficia sin tocar el resto del flujo)",
    ],
  },
  {
    version: "2.45.1",
    date: "2026-08-05",
    changes: [
      "I18N: texto de la hora de la celebración — ahora dice 'La ceremonia dará comienzo a las {{time}} h.' (es) / 'The ceremony will begin at {{time}} h.' (en)",
    ],
  },
  {
    version: "2.45.0",
    date: "2026-08-05",
    changes: [
      "CLEANUP: eliminado el soporte legacy del horario — el campo weddingSchedule (texto libre) ya no se usa en la app: la sección Info solo renderiza el itinerario desde weddingScheduleEvents y se oculta si no hay eventos",
      "CLEANUP: retirado weddingSchedule del esquema (types, defaultConfig, normalize-config, config-validation, codec), del formulario (DateSectionForm ya no siembra eventos desde el texto legacy) y de las reglas de Firestore; añadido al script de limpieza de campos legacy para la BBDD",
      "UX: si el itinerario no se ha configurado, la sección de horario no se muestra en la invitación (antes mostraba 'El horario se compartirá próximamente')",
      "I18N: eliminadas las claves sin uso schedulePending y scheduleTooLong de es/en",
    ],
  },
  {
    version: "2.44.2",
    date: "2026-08-05",
    changes: [
      "FIX: imágenes de la invitación — el auto-guardado (useAutoSave) volvía a guardar couplePhoto como blob cifrado inline (rompía el <img>: 'Failed to load resource') y backgroundImage/customSeal como data-URL inline, re-inflando el documento hasta el límite de 1MB. Ahora migra las imágenes data-URL a la subcolección configImages (refs __cfgimg:) igual que el guardado manual",
      "OPS: re-migrada la invitación leunam (doc de 844KB → 2.7KB) con refs __cfgimg a las copias válidas cifradas en configImages",
    ],
  },
  {
    version: "2.44.1",
    date: "2026-08-05",
    changes: [
      "UX: sección hora/lugar — la hora se muestra como story-note (antes story-copy) y se elimina el mensaje de bienvenida de la sección Detalles",
      "I18N: eliminadas las claves sin uso welcomeWithTime, welcomeWithPlace y welcomeWithoutTime de es/en",
    ],
  },
  {
    version: "2.44.0",
    date: "2026-08-05",
    changes: [
      "FEAT: código de vestimenta — nueva opción 'Otro' que abre un input de texto personalizado (máx 500 caracteres) cuando no sirven las opciones predefinidas",
      "FEAT: campo weddingDressCodeCustom en el esquema (types, defaultConfig, normalize, codec dc->dx) — la invitación muestra el mensaje personalizado cuando el código es 'Otro', y la validación exige ese mensaje (errors.dressCodeCustomRequired/TooLong)",
      "SEGURIDAD: reglas de Firestore — weddingDressCode y weddingDressCodeCustom validados (string, tamaño e isSafeText) en isValidInvitationWrite",
      "VERIFICADO: emulador de Firestore 19/19 — 'Otro' con mensaje permitido, mensaje >500 denegado, dress code predefinido que descarta el custom",
    ],
  },
  {
    version: "2.43.2",
    date: "2026-08-05",
    changes: [
      "UX/I18N: mensaje de bienvenida de la sección Detalles — cuando hay hora, ahora dice 'La celebración dará comienzo a las {{time}}. Te esperamos en la ubicación señalada abajo.' (es/en); eliminada la variante que repetía el lugar en el mensaje con hora (welcomeWithPlaceTime)",
      "CALIDAD: test determinista de token-utils con vi.stubGlobal (la asignación directa a crypto.getRandomValues fallaba en silencio y hacía fluctuar el gate de cobertura) y test de DetailsSection para el caso ubicación sin hora",
    ],
  },
  {
    version: "2.43.1",
    date: "2026-08-05",
    changes: [
      "FIX: recuperación de imágenes — reintentos acotados (300ms/600ms) en getConfigImage ante fallos transitorios de red, para que un blip de conexión no deje la imagen rota de forma permanente",
      "OPS: script scripts/migrate-images-refs.mjs — convierte los campos de imagen inline (data URLs / cifrados legacy) a refs __cfgimg:{id} usando la copia cifrada de configImages; aplicado a la invitación leunam (doc de 527KB → 1.7KB) para que couplePhoto vuelva a cargar",
      "FIX: hint del itinerario (setup.scheduleEventsHint) mostraba literal '{{max}}' — ahora se pasa la interpolación con MAX_SCHEDULE_EVENTS (10)",
    ],
  },
  {
    version: "2.43.0",
    date: "2026-08-05",
    changes: [
      "CALIDAD: cobertura de tests al 90%+ en los 4 umbrales (statements 94.1%, branches 90.0%, functions 93.8%, lines 95.9%) y gate de cobertura actualizado a 90/90/90/90",
      "TESTS: ~180 tests nuevos (1554 → 1732) en hooks (useRsvp, useSetupAuth, useAutoSave, rsvp-payloads), contextos (ConfigContext: visitas, caché, reload, guardado), utils (normalize-config, config-validation, geo-utils, superadmin-utils, image-utils, token-utils, sentry) y componentes (RsvpSection, GallerySection, AttendanceTab, DateSectionForm, TransportSectionForm, CoverSectionForm, HeroSection, PublicInvitation, DashboardTab, PanelTab, App RTL)",
      "CLEANUP: eliminados fallbacks defensivos inalcanzables en useRsvp (los tipos garantizan los arrays de acompañantes) y ramas muertas en config-validation",
      "FIX TEST: token-utils con bytes aleatorios — test determinista que fuerza ambos caminos del generador (la única rama que hacía fluctuar el gate de cobertura)",
    ],
  },
  {
    version: "2.42.0",
    date: "2026-08-04",
    changes: [
      "CLEANUP: auditoría de código legacy — eliminados módulos muertos (session-utils, token-auth-utils, confirm-utils, idb-utils, rsvp-validation, ErrorMessage, barrels lib/index y contexts/index) y exports sin uso (SESSION_RENEW_INTERVAL_MS, SECTION_LABELS, formatDietary, tokenUsageOverTime, rsvpOverTime, parseWeddingDate, RSVP_COLLECTION_REF)",
      "CLEANUP: eliminados los campos legacy de configuración (menuTexto, menuCarne, menuPescado, menuVegano, menuPostre, musicUrl, accommodationInfo, menuHeadcounts, transportInfo) y su código de fallback (formatDishes sin legacy, LegacyEntry/legacyToAttendees, fallbacks en RSVP/Accomodation/Attendance/música)",
      "OPS: tests de reglas actualizados al esquema rsvpResponses/{token}/responses, documentación corregida (leaflet/OSM), umbrales de cobertura ajustados al nuevo estado, y script scripts/cleanup-legacy-fields.mjs (limpieza de campos legacy en la BBDD)",
    ],
  },
  {
    version: "2.41.3",
    date: "2026-08-04",
    changes: [
      "UX: eliminado el campo 'Postre' del formulario — el postre ya forma parte de los platos de cada menú (order: 'postre' en los editores por platos); se retira la obligatoriedad (errors.postreRequired) y la muestra separada en el RSVP",
    ],
  },
  {
    version: "2.41.2",
    date: "2026-08-04",
    changes: [
      "SEGURIDAD: fix de login — la regla de activación exigía sessionExpiresAt >= request.time + 1h, pero el cliente envía (hora cliente) + 60min, que por latencia/reloj es siempre algo menor que request.time + 1h → el login se rechazaba en producción. El mínimo baja a 30min (margen cómodo sobre el TTL de 60min) y se corrige la unidad de minutos (duration.value 'm'). Verificado en emulador 16/16",
    ],
  },
  {
    version: "2.41.1",
    date: "2026-08-04",
    changes: [
      "SEGURIDAD: fix de login — la regla de lectura de setupTokens exigía sesión activa, pero el flujo de login necesita leer setupTokens/{hash} ANTES de activar la sesión (para localizar la invitación por el token). Ahora `get` está permitido sin sesión (el documentId es el hash, ~2^158, no enumerable) y `list` denegado. Verificado en emulador (16/16)",
    ],
  },
  {
    version: "2.41.0",
    date: "2026-08-04",
    changes: [
      "FIX: menú — faltaba el campo 'Postre' en el formulario del setup: la validación lo exigía (errors.postreRequired) y el RSVP lo mostraba, pero no había forma de rellenarlo → guardar con el menú activado fallaba. Añadido el campo y alineada la validación con los editores por platos (*Dishes)",
      "ESQUEMA: las respuestas RSVP ahora se guardan por invitación — rsvpResponses/{inviteToken}/responses/{id} (subcolección) con el contador anti-spam en el documento grupo rsvpResponses/{inviteToken}; se eliminó la colección plana y rsvpCounters; el superadmin agrega vía collectionGroup('responses')",
      "OPS: script scripts/migrate-rsvp-schema.mjs para migrar las RSVP antiguas (colección raíz) al nuevo esquema con firebase-admin",
    ],
  },
  {
    version: "2.40.1",
    date: "2026-08-04",
    changes: [
      "FIX: eliminado el modal del token del setup — el token mostrado en el formulario (input type=password) es ahora el único token y el mismo que se usa para el auto-login al guardar (onFirstSave ya no lo limpia ni lo regenera); tras guardar se muestra la tarjeta de éxito y se redirige al panel",
    ],
  },
  {
    version: "2.40.0",
    date: "2026-08-04",
    changes: [
      "SEGURIDAD: el token de setup ya no se guarda en el documento público de la invitación — nuevo módulo setup-token (hash SHA-256) y colección privada setupTokens con documentId = hash; la activación de sesión exige prueba de conocimiento del token",
      "SEGURIDAD: eliminada la regla de sesión forjable y el 'restore backup' sin validación; la colección invitations ya no es enumerable (solo get); storage.rules requiere sesión activa no expirada; rate limit de RSVP (tope 500 por invitación vía rsvpCounters); reglas de auditLog",
      "SEGURIDAD: validación server-side de campos de texto (longitudes y patrones) en isValidInvitationWrite; sesión en sessionStorage con TTL 60 min; App Check activable por env",
      "SEGURIDAD/CI: sourcemaps de Sentry corregidos en el deploy, reglas (firestore/storage) desplegadas en CI, SECURITY.md y .env.example reintegrados a git",
      "FEAT: creación inicial — el token de acceso se muestra en el formulario (input type=password con mostrar/ocultar) debajo del usuario, con hint y checkbox obligatorio que bloquea el guardado hasta confirmar que se ha guardado",
      "PERF: las props de sección se separaron (config/countdown/rsvp) — el tick del countdown y las teclas del RSVP ya no re-renderizan toda la invitación; el countdown se pausa con pestaña oculta y prefers-reduced-motion",
      "PERF: firebase/analytics movido a chunk lazy (JS inicial 435→315 KB gzip); fuentes de Google por <link> preload; Sentry diferido a idle; caché de RSVP en sessionStorage; fetchPriority en el LCP",
      "ACCESIBILIDAD: focus trap en lightbox de galería y modal de token, skip-link, aria-labels en MusicPlayer, contraste del tema linen-soft, role=alert en login, scope=col en tablas",
      "I18N: fix de claves de alérgenos (se mostraban en español en todos los idiomas), supportedLngs + load languageOnly, hl dinámico en Google Maps, RTL_LANGS corregido, JSON-LD neutro",
      "CALIDAD: fix de mutación directa de estado en RSVP, conteo honesto en la limpieza del superadmin, email de superadmin unificado, check-translations ampliado a los 100 locales (estructura + cobertura) y en CI, check-bundle-size con total inicial real",
      "VERIFICADO: flujo completo de /setup contra el emulador de Firestore (7/7) — setupTokens, primer guardado con todos los campos, sesión con hash correcto/incorrecto, contador RSVP y no enumeración",
    ],
  },
  {
    version: "2.39.0",
    date: "2026-08-04",
    changes: [
      "FEAT: hora de la boda con un único input type=time (HH:MM) — sustituye a los campos de hora y minutos",
      "FEAT: itinerario por eventos — el horario de la boda se configura como eventos (hora + texto corto, máx 10) con siembra desde el texto legacy",
      "FEAT: RSVP — elección de transporte en dos pasos (medio: coche propio/autobús/taxi + salida con nombre del sitio y hora 24h)",
      "FEAT: RSVP — se guardan y recuperan en Firestore el medio, la salida, la hora y el sitio elegidos por invitado y acompañantes",
      "FEAT: tabla de asistencia — nuevas columnas Transporte (medio + hora), Nacimiento y Consentimientos",
      "FEAT: panel /admin — contenedores al 80%, main con overflow hidden, contenido con scroll interno y sin scroll de página (también en móvil)",
      "FEAT: AdminBarHeightSync — --navbar-height mide la altura real de la barra (ResizeObserver), sin solape ni en wrap",
      "FEAT: salidas de transporte — tipo bloqueado y forzado cuando la opción es individual; hora obligatoria con validación HH:MM",
      "FEAT: enlace del mapa de cada salida a línea completa en pantallas pequeñas",
      "ACCESIBILIDAD: IDs únicos en todos los inputs, labels asociados (0 sin asociar, 0 htmlFor rotos), aria-invalid en errores, hints vinculados con aria-describedby",
      "ACCESIBILIDAD: axe audit añadido para la sección RSVP con transporte y menú",
      "FIX: etiquetas de salida usaban transport.optionBus/Taxi (frases completas) — nuevas claves cortas typeBus/typeTaxi",
      "FIX: se guardaba el texto libre de alergias de los acompañantes (companionAllergiesOther) que se perdía",
      "FIX: fecha de nacimiento en la tabla sin hora 0:00",
      "FIX: eliminado código muerto handleDietaryToggle",
      "STYLE: hint 'Lugar detectado' con el nombre del sitio en las salidas del setup",
      "FIX: setup.menuTextoLabel roto (clave anidada setup.setup.*) — promovida al nivel correcto",
      "FIX: alergias del RSVP resolvían por defaultValue (rsvp.allergies.*) — traducción real por idioma",
      "CLEANUP: eliminada dependencia muerta leaflet, 83 claves i18n sin uso, 496 console.log de debug y restos de husky (--version/, lint-staged inerte)",
      "CLEANUP: refactor de useRsvp — payload builders extraídos a módulo puro (rsvp-payloads)",
      "OPS: .gitignore limpiado, .env.example creado, .nvmrc unificado a Node 22, public/index.html duplicado eliminado",
      "CLEANUP: restos de la limpieza de logs (356 sentencias vacías, void err) y 2 warnings de lint eliminados",
      "FEAT: test unitario del módulo rsvp-payloads (6 casos) y e2e ampliado (invitación inexistente sin crash)",
      "FIX: script check-translations.js roto (require en repo ESM) — convertido a ESM y funcional",
      "OPS: umbrales de coverage ajustados al estado real (85/81/86/87) y CSP sin restos de Leaflet/OSM/goo.gl",
      "FIX: common.remove inexistente — el aria-label del botón de eliminar acompañante mostraba 'Remove' en español",
      "UX: rsvp.description reescrita — texto neutro que cubre menú, alergias y transporte (antes mencionaba 'menú especial' siempre)",
      "SEGURIDAD: reglas de Firestore — rsvpResponses no permitía los 8 campos nuevos de transporte (hasOnly) → el guardado del RSVP con transporte se rechazaba en producción (PERMISSION_DENIED). Añadidos a create/update con validación de tipos y longitudes, y reglas desplegadas (el deploy habitual solo sube hosting).",
      "SEGURIDAD: verificado con emulador de Firestore (8/8) — RSVP main/companion con transporte permitidos, campos extra y horas inválidas rechazados, setup con weddingScheduleEvents/transportDepartures permitido",
      "FIX: tabla de asistencia — la columna de dieta mostraba 'alergia: 1' (conteo sin sentido en registros nuevos) y la de menú '—' (menuHeadcounts no se guarda); ahora muestran los items y el plato elegido (mealChoice)",
      "FEAT: alojamiento como enlace de Google Maps — nuevo campo accommodationURL en el setup (validación y hint del sitio) y la sección muestra el nombre, el mapa y 'Ver en Google Maps', con fallback al texto legacy",
      "FEAT: menú por platos — nuevo editor (como salidas de transporte) con orden predefinido (Entrante/Primero/Segundo/Tercero/Postre/Otro) y añadir/eliminar platos, tanto para el menú fijo (menuTextoDishes) como para los seleccionables (menuCarneDishes/Pescado/Vegano); el RSVP muestra los platos formateados con fallback al texto legacy",
      "VERIFICADO: flujo de guardado del menú por platos (form → normalize → validación → payload Firestore → recuperación) con tests de persistencia round-trip, guardado en ConfigContext y rechazo de órdenes inválidas",
      "FIX: menú fijo no se mostraba en el RSVP — el bloque solo se renderizaba con menuEnabled=true; ahora el menú fijo (menuEnabled=false) muestra los platos sin selector, y el variable muestra el selector con el menú de la opción debajo",
      "FIX i18n: 10 claves usadas sin texto añadidas (se mostraban crudas): hero.sectionLabel, admin.tabs.ariaLabel, errors.generic/restoreFailed, rsvp.validation.guestNamesExceed/Required y headcountExceed, settings.menuChangeConfirm, setup.cornerDecorationUploadHint y transportTypeLabel. Auditoría exhaustiva: 0 claves literales sin resolver y todos los valores dinámicos (temas, meses, idiomas, compliance, alergias, platos) verificados",
      "FIX i18n: textos hardcodeados en atributos — MapEmbed (title español), DateSectionForm preview (title inglés) e InvitationTab (aria-label inglés) pasan a claves; invitación y setup sin textos crudos",
      "FIX i18n: hints desactualizados — setup.menuHint y menuTextoHint ahora describen platos con orden, y guestsSectionHint ya no menciona transporte (sección propia)",
    ],
  },

  {
    version: "2.38.0",
    date: "2026-08-01",
    changes: [
      "FEAT: nueva sección Transporte en la invitación y en la configuración",
      "FEAT: opciones de transporte (autobús/taxi/ambos/ninguno) — si no se elige ninguna, mensaje pidiendo coche propio",
      "FEAT: salidas con hora y URL de mapa (hasta 4, añadir/eliminar desde el setup)",
      "FEAT: cada salida muestra su iframe de Google Maps en la invitación",
      "FEAT: MapEmbed — componente de iframe de mapa generalizado (hereda vista/estático del invitación, ancho 80%)",
      "FEAT: transporte sustituye al antiguo texto libre transportInfo (migración de sectionOrder añadiendo la sección)",
      "VALIDACIÓN: transportEnabled whitelist, salidas JSON (máx 4), hora HH:MM, URLs de mapa válidas",
      "FEAT: salidas y enlaces guardados en Firestore + codec hash (te/td)",
    ],
  },

  {
    version: "2.37.0",
    date: "2026-08-01",
    changes: [
      "FEAT: weddingSiteURL reemplaza lat/lng — nombre del lugar derivado de la URL (extractPlaceNameFromUrl), sin geocodificación",
      "FEAT: solo URLs google.com/maps/place/... — enlaces cortos y búsquedas rechazadas con validación visual (badge ✓/✗, caja de feedback, instrucciones)",
      "FEAT: opciones de mapa configurables — vista mapa/satélite/híbrido y mapa estático (bloqueo de interacción)",
      "FEAT: custom background en contenedor propio (.story-card-wrap) — estático frente al scroll, por encima del tema, ajuste cover",
      "FEAT: esquinas decorativas y patrón con la anchura exacta de la card y por encima del background del tema",
      "FEAT: sección fecha y lugar reordenada — fecha+hora, calendario, ubicación, mapa, transporte, mensaje (con variantes según datos pendientes)",
      "FEAT: RSVP — postre tras elegir menú (y en menú fijo), encima de alergias",
      "FEAT: story-eyebrow con Great Vibes, colores por tema (azul medianoche claro / marfil oscuro) y mayor que el título; título -20%",
      "FEAT: cuenta atrás calendárica (años/meses/días) con corte en el primer cero",
      "FEAT: escala z-index reordenada — envelope arriba (fondo 10000, sobre 10001, textos 10002), navbar sobre secciones, textos +1 sobre su padre",
      "FEAT: envelope — fondo difuminado (blur 160px + fallback opaco), sobre más grande, sello custom circular que llena la cera",
      "FEAT: luciérnagas con más brillo (punto 4px, glow ampliado, brightness 1.1-1.5)",
      "FEAT: cards con altura máxima calc(100dvh - navbar - clamp) y scroll interno en todas las secciones",
      "FIX: compressImage saltaba la reducción de dimensiones en JPEGs pequeños (<300KB) — i/o Error en Safari",
      "FIX: CSP — maps.google.com/www.google.com en frame-src (meta+header); iframe del mapa bloqueado en producción",
      "FIX: setup layout/card sin altura fija ni scroll propio — crece con el contenido y el inicio es alcanzable",
      "FIX: e2e CI — webServer con cwd de la raíz del repo (Playwright usaba e2e/ y vite preview servía 404)",
      "FIX: html/body min-height 100dvh y secciones min-height 100dvh con overflow propio",
      "STYLE: iframe del mapa con borde y glow acorde a la página",
    ],
  },

  {
    version: "2.36.1",
    date: "2026-07-31",
    changes: [
      "FEAT: piezas enterprise — bump automático, preview channels por PR, Sentry release+sourcemaps, load test k6, docs/OPS.md",
      "FIX: bump-version.js convertido a ESM",
      "FIX: slugs Sentry correctos (solo-developer-p9 / wedingo-6c26a)",
    ],
  },

  {
    version: "2.36.0",
    date: "2026-07-31",
    changes: [
      "FEAT: Google Maps URL en vez de Leaflet/OSM — nuevo campo weddingMapUrl en config",
      "FEAT: DateSectionForm reescrita — input de URL con validación + iframe preview",
      "FEAT: WeddingMap simplificado — solo recibe mapUrl, sin geocodificación",
      "FEAT: DetailsSection usa weddingMapUrl directamente, sin locationMapTarget",
      "FEAT: isValidGoogleMapsUrl + convertToEmbedUrl en geo-utils",
      "CLEANUP: eliminado useMapPreview hook y map-utils (OSM tile canvas)",
      "CLEANUP: eliminado locationMapTarget/Error/Loading de UIContext",
      "CLEANUP: eliminado OSM search (searchLocations, handlePlaceChange, geocodeLocation)",
    ],
  },

  {
    version: "2.35.0",
    date: "2026-07-31",
    changes: [
      "FIX: normalizeConfig omitía backgroundImage, customSeal, cornerDecoration — no se resolvían desde subcolección",
      "FIX: audio upload excedía límite 11MB — chunk 500KB→200KB, batches múltiples en addAudio",
      "STYLE: unificados estilos de upload en todo el formulario (hover, padding, fonts)",
      "STYLE: divisores centrados (eliminado margin inline que los desplazaba a la izquierda)",
      "STYLE: nueva clase CSS .setup-checkbox-label, eliminados inline styles en SetupForm",
      "FEAT: changelog reescrito desde cero con todos los commits reflejados",
    ],
  },
  {
    version: "2.34.0",
    date: "2026-07-30",
    changes: [
      "FEAT: Google Maps Embed reemplaza Leaflet — WeddingMap simplificado a iframe sin API key",
      "FEAT: buildGoogleMapsEmbedUrl / buildGoogleMapsEmbedSearchUrl en geo-utils",
      "CLEANUP: eliminado Leaflet (mapa, tipos, dependencia npm, ~350 líneas de código)",
      "DEBUG: logs [app] exhaustivos en 30 archivos (páginas, hooks, contextos, servicios)",
      "FIX: PrintPage ",
      "FIX: .story-card::before opacity 0.15→0.3 para mejor visibilidad del background",
      "FIX: canvasToType fallback JPEG→PNG (preserva transparencia siempre)",
      "FIX: resolveAllConfigImages también ejecutado desde caché (no solo desde Firestore)",
      "FIX: session restore repara activeSession si falta en Firestore (sesiones huérfanas)",
      "FIX: reglas Firestore configImages create/update separadas (diff fallaba en create)",
      "FIX: compressImage sin fondo blanco (ya no JPEG, usa WebP/PNG con alpha)",
      "FIX: test isolation en useSetupAuth (mockGetSession no persistía entre tests)",
    ],
  },
  {
    version: "2.33.0",
    date: "2026-07-30",
    changes: [
      "FEAT: config images migradas a subcolección Firestore — evita truncado por límite 1MB",
      "FEAT: saveConfigImage / getConfigImage / deleteConfigImage / resolveAllConfigImages",
      "FEAT: useConfigImage hook para resolver refs __cfgimg:xxx en componentes",
      "FIX: CoverSectionForm uploads con try-catch + límite 900KB (subcolección permite 1MB)",
      "FIX: CoverSectionForm previews usan useConfigImage para resolver refs",
      "FIX: handleDeleteInvitation también borra configImages",
      "FIX: reglas Firestore para configImages subcollection",
      "FIX: cache de configuración también resuelve referencias de imágenes",
    ],
  },
  {
    version: "2.32.0",
    date: "2026-07-29",
    changes: [
      "FEAT: AttendanceTab CRUD completo — checkboxes selección individual, delete batch",
      "FEAT: columna 'Acompañante de' en tabla de asistencia (mainGuestName)",
      "FEAT: handleDeleteRsvpEntries en useRsvp — delete batch con writeBatch",
      "UI: filtro de búsqueda incluye acompañantes vinculados al invitado principal",
      "FIX: prefill RSVP restaura todos los campos (birthDate, allergies, consents, etc.)",
      "FIX: prefill también funciona para acompañantes (rsvpType === 'companion')",
      "FIX: banner 'Acompañas a X' para acompañantes en RSVP",
      "FIX: campo nombre siempre editable aunque haya match (se puede borrar y cambiar)",
      "FIX: z-index backgrounds (invite-bg, corner, eucalyptus) a 0 (estaban tapando)",
      "FIX: body::before glow estático → body directo con animación + body::after animado",
      "FIX: eliminar skip-link (HTML, CSS, RTL) — sin uso",
      "FIX: eliminar theme-glow-pulse por completo",
      "FIX: theme glow en body directo (sin pseudo-elementos before/after)",
      "FIX: backgroundImage como fondo de story-cards (CSS var) en vez de fixed page bg",
      "FIX: retirar asistencia también borra acompañantes del estado local",
      "I18N: nuevas claves attendance.tableAccompanies, selectAll, selectEntry, deleteSelected*",
    ],
  },
  {
    version: "2.31.0",
    date: "2026-07-29",
    changes: [
      "FEAT: acompañantes requieren mismos datos obligatorios que invitado principal",
      "FEAT: companionBirthDates, companionParentalConsents, companionHealthConsents en formulario",
      "FIX: companionAllergies como string[] (Firestore no soporta arrays anidados)",
      "FIX: incluir companions como entradas individuales en lista de asistencia",
    ],
  },
  {
    version: "2.30.0",
    date: "2026-07-28",
    changes: [
      "FEAT: cornerDecoration unificado — 1 sola imagen para las 4 esquinas (antes 4 uploads)",
      "FIX: cornerDecoration con compressImageTransparent (preserva transparencia PNG)",
      "FIX: readFileAsDataUrl añadido a image-utils (para cornerDecoration sin compresión)",
      "REFS: cornerDecorationTL/TR/BL/BR eliminados, ahora cornerDecoration único",
    ],
  },
  {
    version: "2.29.0",
    date: "2026-07-28",
    changes: [
      "FIX: onFirstSave espera updateDoc antes de setIsTokenVerified (sesión huérfana)",
      "FIX: race condition restauración sesión + isRestoringSession loading state",
      "FIX: sesión persistente en localStorage en vez de sessionStorage (cierre navegador)",
      "FIX: falta companionDocIds en hasOnly de Firestore rules",
      "FIX: ocultar postre si no asiste",
      "FIX: login no sobrescribe sesión existente (rules + LandingPage tx)",
      "FIX: companion healthConsent rules + console.error debug en uploads",
      "FIX: mensajes i18n RSVP más user-friendly (EN+ES)",
      "FEAT: cada acompañante con su propio documento Firestore (writeBatch + rules)",
      "DEBUG: logs restauración sesión",
    ],
  },
  {
    version: "2.28.0",
    date: "2026-07-27",
    changes: [
      "CALIDAD: cobertura 34.96%→~87%, 291→1611 tests, 141 test files",
      "CALIDAD: 0 lint warnings, 0 typecheck errors, 0 any en source",
      "CALIDAD: CSS !important 48→41, @fontsource eliminado, CSS @import order corregido",
      "SEGURIDAD: gallery/audio delete requiere auth en Firestore rules, CSP style-src unsafe-inline",
      "SEGURIDAD: session renewal fix, PasswordCredential typings",
      "CI/CD: typecheck, JUnit reporter, bundle size, coverage thresholds, deploy automático, dependabot",
      "UI: foto novios redonda con borde dorado animado, fondo blanco para PNG con transparencia",
      "UI: contenedores invitación 90% base, 80% en móvil",
      "UI: botón accesibilidad visible en /admin, changelog modal 40%x80%",
      "UX: export/restore rediseñado, secciones alojamiento/transporte movidas a 'Sobre los invitados'",
      "UX: menú muestra descripción al seleccionar, contador no asistentes, singular/plural attendee",
      "RENDIMIENTO: sourcemaps condicionales, Sentry lazy load, vendor chunk splitting",
      "RENDIMIENTO: Service Worker v2, fuentes Google CDN, preconnect Firebase/Google",
      "RENDIMIENTO: Playwright E2E config + CI, axe-core a11y tests por página",
      "BUGFIX: session renewal enviaba solo sessionExpiresAt (rules esperaban ambos campos)",
      "BUGFIX: ConfigContext OOM dividido en 3 archivos, image-store flaky test",
      "BUGFIX: restore error mensaje, i18n clave errorDetail",
      "DEPS: TypeScript 7, jsdom 30, jest-dom 7, oxlint 1.76, @fontsource eliminados",
      "MONITORING: Sentry (prod 0.1, dev 0), Firebase Analytics, web-vitals",
      "DOCS: ARCHITECTURE.md, BROWSER_COMPAT.md, SECRETS.md, SECURITY.md, .nvmrc",
    ],
  },
  {
    version: "2.27.0",
    date: "2026-07-27",
    changes: [
      "CALIDAD: 316 typecheck errors → 0, strict flags (noUncheckedIndexedAccess, noImplicitOverride, exactOptionalPropertyTypes)",
      "CALIDAD: lint 17→0 warnings, any en source ~80→0, !important CSS 48→41",
      "TESTS: 36→127 test files, 291→1214 tests, cobertura 34.96%→75.36%",
      "TESTS: axe-core a11y, Firestore rules simulation, 7 setup-forms, 13 componentes",
      "ARQUITECTURA: hooks separados de context providers (Fast Refresh), barrel exports",
      "I18N: RSVP traducciones corregidas, errores tipográficos",
      "RSVP: rediseñado a modelo individual, menú con descripción, singular/plural attendee",
      "UI: foto novios redonda con fusión radial, nombres escalados, overflow admin corregido",
      "SEGURIDAD: CSP corregido, notAttendingCount en rules, _visits permitido",
      "RENDIMIENTO: sourcemaps condicionales, Sentry lazy load, vendor chunk splitting",
      "RENDIMIENTO: Service Worker v2, fuentes Google CDN, preconnect Firebase/Google",
      "BUGFIX: gallery/music upload crypto, RSVP i18n keys, image-store flaky test",
      "CI/CD: typecheck, JUnit, bundle size, coverage thresholds, dependabot, deploy automático",
      "DEPS: TypeScript 7, jsdom 30, jest-dom 7, oxlint 1.76",
    ],
  },
  {
    version: "2.26.0",
    date: "2026-07-26",
    changes: [
      "AUDITORÍA: ~120 puntos implementados de 250 identificados",
      "FIX: 10 altos — offline, timeout, rate limit, CSP, Sentry, CI/CD, LCP, privacidad, context split",
      "FIX: 10 medios — RTL, JSDoc, cobertura, ARIA, errores, skip-link, atajos, validación",
      "FIX: batch bajos — GalleryManager, CSS vars, z-index, import cleanup, naming, lazy loading",
      "FIX: RTL, ErrorBoundary, tests, tipos, almacenamiento, focus-visible, accesibilidad",
      "FIX: robots, schema.org, architecture.md, check-translations script",
      "FIX: WebP, tipos, validaciones, ARIA, tests, RTL, animaciones",
      "FIX: safe-areas, touch-action, print, suspenso, tests, backdrop-filter, indexedDB",
      "FIX: SW, PWA, offline, i18n, validación, seguridad, scroll, preload, tests",
      "FIX: IBAN validation, aria-live search, tests, memo checks",
      "REFACTOR: AttendanceTab columnas por persona, RSVP por asistentes individuales",
      "FIX: zoom 400% — media queries ≤480px y ≤360px",
      "FIX: Safari prefixes backdrop-filter y user-select",
      "FIX: admin bar username desde getSession()",
      "FIX: reject cookies no borra sesión",
      "TESTS: +99 tests (7 módulos, 13 componentes), coverage thresholds",
    ],
  },
  {
    version: "2.25.0",
    date: "2026-07-25",
    changes: [
      "AUDITORÍA: 50+ puntos, README, CHANGELOG actualizados",
      "FEAT: popup confirmación si hay RSVPs al cambiar menú",
      "FIX: i18n completo — offline, countdown, menús, dietas, fecha, impresión, versión",
      "FIX: attendees model — total invitados = suma de attendees.length",
      "FIX: foto novios 700px, 4:3, border-radius 1.5rem, mask-image radial",
      "FIX: botones mapa/calendario padding 2%",
      "CI: bundle size check, coverage thresholds, Sentry, dependabot",
    ],
  },
  {
    version: "2.24.0",
    date: "2026-07-24",
    changes: [
      "FIX: MAX_DURATION_SEC 30→20s (doble base64 excedía 1MB Firestore)",
      "FEAT: autoplay + loop en MusicPlayer",
      "FEAT: modal con setupToken tras crear invitación",
      "FIX: navigator.credentials.store en login (browser guarda credenciales)",
      "FIX: autoplay sincroniza estado playing con ecualizador",
      "FIX: AccessTab simplificado (sin confirmación)",
      "FIX: hero.eyebrow array→string en 85 idiomas",
    ],
  },
  {
    version: "2.23.0",
    date: "2026-07-23",
    changes: [
      "FIX: crítico — musicFile se perdía tras save (delete sin restaurar)",
      "FIX: music-player z-index 10001 (por debajo del nav-overlay 10002)",
      "FIX: envelope timing más lento y fluido (flap 1.2s, letter fade 1.2s + delay 0.5s)",
      "FIX: overflow hidden envelope",
      "FEAT: SupportTab 2 columnas + uploads unificados con estilo galería",
      "FEAT: autoplay en mobile via custom event desde envelope tap",
    ],
  },
  {
    version: "2.22.0",
    date: "2026-07-22",
    changes: [
      "FIX: MusicArrayEditor sin controles nativos (Safari AirPlay error)",
      "FIX: error handling masivo (useSetupAuth + AuthContext + traducciones)",
      "FIX: restore backup (Firestore rules + preservar sesión)",
      "FIX: CRÍTICO — sesión Firestore nunca renovada",
    ],
  },
  {
    version: "2.21.0",
    date: "2026-07-21",
    changes: [
      "FIX: 15 silent catches convertidos a toasts de error",
      "FIX: audio comprimido sonaba lento y con reverb (resampling manual incorrecto)",
      "FEAT: audio chunked (22050Hz, 60s, dividido en fragmentos de 500KB)",
      "REFACTOR: gallery+audio como subcolecciones de invitations/{token}",
      "FEAT: login valida username contra adminUsername",
    ],
  },
  {
    version: "2.20.0",
    date: "2026-07-20",
    changes: [
      "FIX: music upload redesign (audioData collection, gallery-like UI)",
      "FEAT: MusicArrayEditor en CoverSectionForm (no sección separada)",
      "FIX: auto-save debounce 3s→1.5s",
      "FIX: audio sin límite de duración (canción completa)",
      "FIX: admin bar muestra username en vez de inviteToken",
    ],
  },
  {
    version: "2.19.0",
    date: "2026-07-19",
    changes: [
      "FIX: audio upload (compressAudio), restore cleanup",
      "FIX: couple photo infinite loading + loading spinner en galería",
      "FIX: GallerySection null currentTarget.dataset error",
    ],
  },
  {
    version: "2.18.0",
    date: "2026-07-18",
    changes: [
      "FIX: críticos (location, readFileAsDataUrl, chart-utils, cascadeDelete) + altos",
      "FIX: background image 100K gate eliminado",
      "FIX: couplePhoto loading infinito corregido",
    ],
  },
  {
    version: "2.17.0",
    date: "2026-07-17",
    changes: [
      "FIX: restore backup (Firestore rules + preservar sesión)",
      "FIX: CRÍTICO sesión Firestore nunca renovada",
      "FIX: restore usa updateDoc en vez de setDoc",
      "FIX: app-scene top offset",
    ],
  },
  {
    version: "2.16.0",
    date: "2026-07-16",
    changes: [
      "I18N: +14 idiomas (99 total)",
      "FEAT: nuevo idioma Panyabí (pa)",
      "FIX: alturas contenedores (story-section, body, app-scene, footer)",
      "FIX: overflow admin panels (setup-card--wide height)",
      "FIX: solapamiento secciones admin (setup-form stretch)",
      "FIX: botones mapa/calendario padding 2%",
      "FIX: godparents text glow animado con var(--flower-accent)",
    ],
  },
  {
    version: "2.15.0",
    date: "2026-07-15",
    changes: [
      "SEO: PWA manifest, font preload, loading=lazy, título dinámico",
      "I18N: 82/82 idiomas completos, traducciones nativas 16 idiomas",
      "FIX: RTL, aria-invalid RSVP, console.warn eliminado",
      "FIX: DataTab CSS, dead props eliminados",
      "FIX: validación archivos vacíos en todos los uploads",
      "FIX: traducciones ES/EN incorrectas propagadas a 80 idiomas",
    ],
  },
  {
    version: "2.14.0",
    date: "2026-07-14",
    changes: [
      "PERF: CSS muerto eliminado, touch targets 44px, lazy modales",
      "FIX: revert lazy LegalModal/ChangelogModal (imports estáticos)",
      "REFACTOR: TokensTab y DataTab migrados a clases CSS",
      "FIX: RTL toast, aria añadido",
    ],
  },
  {
    version: "2.13.0",
    date: "2026-07-13",
    changes: [
      "PERF: bundle 9.0→6.1MB, fuentes latin-only, vendor chunk",
      "FIX: PanelTab inviteToken undefined",
      "FIX: AttendanceTab formatDate desde config",
      "FIX: RSVP responsive + input date mobile",
      "FIX: PrintPage solo mensaje+fecha+ubicación",
    ],
  },
  {
    version: "2.12.0",
    date: "2026-07-12",
    changes: [
      "FIX: eliminar SoundCloud, nuevo AudioUploadPicker con subida de ficheros",
      "FIX: AttendanceTab crash rsvpEntries/filteredEntries undefined",
      "FIX: eliminar botones Vista previa y Como invitado de /admin",
      "FIX: MusicPlayer animaciones elegantes, FAB desplazamiento",
      "FIX: NavBar sticky/fixed, PrintPage reescrita desde cero",
    ],
  },
  {
    version: "2.11.0",
    date: "2026-07-11",
    changes: [
      "FIX: sello de cera realista en solapa + fuentes más grandes",
      "FIX: nombres al borde inferior del envelope",
      "FIX: sello subido ligeramente, sombra en solapa",
      "FIX: fondo animado con profundidad radial y brillo",
    ],
  },
  {
    version: "2.10.0",
    date: "2026-07-10",
    changes: [
      "FEAT: envelope realista (papel crema, sombra, luces orbitales)",
      "FIX: scroll bloqueado mientras envelope visible",
      "TESTS: +113 tests en 9 módulos, bugfix crypto (iter count 2→3 bytes)",
      "FIX: CSP font-src data: permitido",
    ],
  },
  {
    version: "2.9.0",
    date: "2026-07-09",
    changes: [
      "FEAT: TypeScript migration",
      "FIX: security hardening, SoundCloud picker",
      "FIX: accessibility — focus visible, aria, contraste",
    ],
  },
  {
    version: "2.8.0",
    date: "2026-07-08",
    changes: [
      "REFACTOR: CSS modularizado en 15 archivos (gallery, envelope, music, a11y, lang, toast, print, admin, modals, landing, decorations)",
      "FEAT: fireflies animados (24 unidades, 6 colores, 4 trayectorias)",
      "FIX: footer siempre visible, admin bar separada",
      "FIX: z-index modales 10001 (por encima envelope 9999)",
    ],
  },
  {
    version: "2.7.0",
    date: "2026-07-07",
    changes: [
      "FEAT: envelope animado con flash blanco, texto dorado, glow orbital",
      "FEAT: dos clics — primero abre, segundo animación de salida",
      "FEAT: unificación hero con story-card, mismos estilos",
      "FIX: reglas Firestore gallery update/delete mejoradas",
      "FIX: gallery caption con fade+slide, blur→unblur 1.8s",
    ],
  },
  {
    version: "2.6.0",
    date: "2026-07-06",
    changes: [
      "FEAT: galería con 10 slots fijos, galleryData como fuente única",
      "FEAT: CRUD completo en galería con orden persistente",
      "FIX: loadGallery sin orderBy (falta índice), sort client-side",
      "FIX: descripciones cifradas, fondo gradiente en imagen",
    ],
  },
  {
    version: "2.5.0",
    date: "2026-07-05",
    changes: [
      "FEAT: nueva colección galleryData (inviteToken, position, data)",
      "FIX: RSVP form con scroll interior, overflow controlado",
      "FIX: TDZ persistOrder en GalleryArrayEditor",
    ],
  },
  {
    version: "2.4.0",
    date: "2026-07-04",
    changes: [
      "FEAT: scroll-snap CSS nativo reemplaza JS navigation",
      "FIX: body::before fijo fullscreen, app-scene bg, secciones min-height",
      "FIX: fondo elegante con glow radial por tema en body",
      "FEAT: luciérnagas animadas + glow elegante",
      "FIX: galería 10 imágenes máx, ordenada por createdAt",
    ],
  },
  {
    version: "2.3.0",
    date: "2026-07-03",
    changes: [
      "FEAT: fondos body por tema con decoraciones florales CSS",
      "FIX: showRsvp condicional a config, RsvpSection eager load",
      "FIX: isSavingRef trabado por auto-save (nunca se reseteaba)",
      "FIX: body bg Safari (remove background-attachment fixed)",
    ],
  },
  {
    version: "2.2.0",
    date: "2026-07-02",
    changes: [
      "FEAT: RSVP acompañantes/menú, animación sobre, fondos por tema",
      "FIX: sobre realista y fondos animados por tema",
      "FIX: RSVP visible con Suspense, campos nombres invitados, validaciones",
      "I18N: envelope y calendar strings, scan completo de hardcoded strings",
    ],
  },
  {
    version: "2.1.0",
    date: "2026-07-01",
    changes: [
      "FEAT: 76+ idiomas i18n (react-i18next), LanguageSwitcher",
      "FEAT: compliance GDPR/CCPA/LGPD/PIPEDA/POPIA + cookie consent + derechos ARSO",
      "FEAT: registro Art. 30 GDPR, compliance tab en superadmin",
      "FEAT: animaciones de salida en modales y popup idioma",
      "FIX: estructura namespaces i18n, dot notation final",
      "FIX: gatear localStorage/sessionStorage tras consentimiento",
    ],
  },
  {
    version: "2.0.1",
    date: "2026-06-30",
    changes: [
      "FEAT: accesibilidad — 8 opciones (OpenDyslexic, alto contraste, escala grises, foco visible)",
      "FEAT: footer con legal, idioma, accesibilidad y versión",
      "FEAT: changelog completo desde inicio del desarrollo",
      "FIX: navbar sticky, admin-bar offset, overflow inferior",
      "FIX: CSP font-src, frame-ancestors meta, firebase getFirestore",
      "FIX: galería con progress bar real, miniaturas en tiempo real",
      "FIX: carrusel automático 1.5s, descripciones editables",
      "FEAT: superadmin — export/eliminación individual, masiva y completa",
      "FIX: sesiones migradas a activeSession en invitación",
      "FIX: XSS innerHTML → createElement",
      "FIX: footer redes sociales, copyright y copyright del programador",
    ],
  },
];
