export const CHANGELOG = [
  {
    version: "2.35.0",
    date: "2026-07-31",
    changes: [
      "FIX: normalizeConfig omitía backgroundImage, customSeal, cornerDecoration — no se resolvían desde subcolección",
      "FIX: audio upload excedía límite 11MB — chunk 500KB→200KB, batches múltiples en addAudio",
      "STYLE: unificados estilos de upload en todo el formulario (hover, padding, fonts)",
      "STYLE: divisores centrados (eliminado margin inline que los desplazaba a la izquierda)",
      "STYLE: nueva clase CSS .setup-checkbox-label, eliminados inline styles en SetupForm",
      "FEAT: changelog reescrito desde cero con todos los commits reflejados",
    ],
  },
  {
    version: "2.34.0",
    date: "2026-07-30",
    changes: [
      "FEAT: Google Maps Embed reemplaza Leaflet — WeddingMap simplificado a iframe sin API key",
      "FEAT: buildGoogleMapsEmbedUrl / buildGoogleMapsEmbedSearchUrl en geo-utils",
      "CLEANUP: eliminado Leaflet (mapa, tipos, dependencia npm, ~350 líneas de código)",
      "DEBUG: logs [app] exhaustivos en 30 archivos (páginas, hooks, contextos, servicios)",
      "FIX: PrintPage console.log accedía a isConfigLoading antes de inicializarse",
      "FIX: compressImageTransparent ahora usa WebP+calidad+dimensión (no PNG directo)",
      "FIX: .story-card::before opacity 0.15→0.3 para mejor visibilidad del background",
      "FIX: canvasToType fallback JPEG→PNG (preserva transparencia siempre)",
      "FIX: resolveAllConfigImages también ejecutado desde caché (no solo desde Firestore)",
      "FIX: session restore repara activeSession si falta en Firestore (sesiones huérfanas)",
      "FIX: reglas Firestore configImages create/update separadas (diff fallaba en create)",
      "FIX: compressImage sin fondo blanco (ya no JPEG, usa WebP/PNG con alpha)",
      "FIX: test isolation en useSetupAuth (mockGetSession no persistía entre tests)",
    ],
  },
  {
    version: "2.33.0",
    date: "2026-07-30",
    changes: [
      "FEAT: config images migradas a subcolección Firestore — evita truncado por límite 1MB",
      "FEAT: saveConfigImage / getConfigImage / deleteConfigImage / resolveAllConfigImages",
      "FEAT: useConfigImage hook para resolver refs __cfgimg:xxx en componentes",
      "FIX: CoverSectionForm uploads con try-catch + límite 900KB (subcolección permite 1MB)",
      "FIX: CoverSectionForm previews usan useConfigImage para resolver refs",
      "FIX: handleDeleteInvitation también borra configImages",
      "FIX: reglas Firestore para configImages subcollection",
      "FIX: cache de configuración también resuelve referencias de imágenes",
    ],
  },
  {
    version: "2.32.0",
    date: "2026-07-29",
    changes: [
      "FEAT: AttendanceTab CRUD completo — checkboxes selección individual, delete batch",
      "FEAT: columna 'Acompañante de' en tabla de asistencia (mainGuestName)",
      "FEAT: handleDeleteRsvpEntries en useRsvp — delete batch con writeBatch",
      "UI: filtro de búsqueda incluye acompañantes vinculados al invitado principal",
      "FIX: prefill RSVP restaura todos los campos (birthDate, allergies, consents, etc.)",
      "FIX: prefill también funciona para acompañantes (rsvpType === 'companion')",
      "FIX: banner 'Acompañas a X' para acompañantes en RSVP",
      "FIX: campo nombre siempre editable aunque haya match (se puede borrar y cambiar)",
      "FIX: z-index backgrounds (invite-bg, corner, eucalyptus) a 0 (estaban tapando)",
      "FIX: body::before glow estático → body directo con animación + body::after animado",
      "FIX: eliminar skip-link (HTML, CSS, RTL) — sin uso",
      "FIX: eliminar theme-glow-pulse por completo",
      "FIX: theme glow en body directo (sin pseudo-elementos before/after)",
      "FIX: backgroundImage como fondo de story-cards (CSS var) en vez de fixed page bg",
      "FIX: retirar asistencia también borra acompañantes del estado local",
      "I18N: nuevas claves attendance.tableAccompanies, selectAll, selectEntry, deleteSelected*",
    ],
  },
  {
    version: "2.31.0",
    date: "2026-07-29",
    changes: [
      "FEAT: acompañantes requieren mismos datos obligatorios que invitado principal",
      "FEAT: companionBirthDates, companionParentalConsents, companionHealthConsents en formulario",
      "FIX: companionAllergies como string[] (Firestore no soporta arrays anidados)",
      "FIX: incluir companions como entradas individuales en lista de asistencia",
    ],
  },
  {
    version: "2.30.0",
    date: "2026-07-28",
    changes: [
      "FEAT: cornerDecoration unificado — 1 sola imagen para las 4 esquinas (antes 4 uploads)",
      "FIX: cornerDecoration con compressImageTransparent (preserva transparencia PNG)",
      "FIX: readFileAsDataUrl añadido a image-utils (para cornerDecoration sin compresión)",
      "REFS: cornerDecorationTL/TR/BL/BR eliminados, ahora cornerDecoration único",
    ],
  },
  {
    version: "2.29.0",
    date: "2026-07-28",
    changes: [
      "FIX: onFirstSave espera updateDoc antes de setIsTokenVerified (sesión huérfana)",
      "FIX: race condition restauración sesión + isRestoringSession loading state",
      "FIX: sesión persistente en localStorage en vez de sessionStorage (cierre navegador)",
      "FIX: falta companionDocIds en hasOnly de Firestore rules",
      "FIX: ocultar postre si no asiste",
      "FIX: login no sobrescribe sesión existente (rules + LandingPage tx)",
      "FIX: companion healthConsent rules + console.error debug en uploads",
      "FIX: mensajes i18n RSVP más user-friendly (EN+ES)",
      "FEAT: cada acompañante con su propio documento Firestore (writeBatch + rules)",
      "DEBUG: logs restauración sesión",
    ],
  },
  {
    version: "2.28.0",
    date: "2026-07-27",
    changes: [
      "CALIDAD: cobertura 34.96%→~87%, 291→1611 tests, 141 test files",
      "CALIDAD: 0 lint warnings, 0 typecheck errors, 0 any en source",
      "CALIDAD: CSS !important 48→41, @fontsource eliminado, CSS @import order corregido",
      "SEGURIDAD: gallery/audio delete requiere auth en Firestore rules, CSP style-src unsafe-inline",
      "SEGURIDAD: session renewal fix, PasswordCredential typings",
      "CI/CD: typecheck, JUnit reporter, bundle size, coverage thresholds, deploy automático, dependabot",
      "UI: foto novios redonda con borde dorado animado, fondo blanco para PNG con transparencia",
      "UI: contenedores invitación 90% base, 80% en móvil",
      "UI: botón accesibilidad visible en /admin, changelog modal 40%x80%",
      "UX: export/restore rediseñado, secciones alojamiento/transporte movidas a 'Sobre los invitados'",
      "UX: menú muestra descripción al seleccionar, contador no asistentes, singular/plural attendee",
      "RENDIMIENTO: sourcemaps condicionales, Sentry lazy load, vendor chunk splitting",
      "RENDIMIENTO: Service Worker v2, fuentes Google CDN, preconnect Firebase/Google",
      "RENDIMIENTO: Playwright E2E config + CI, axe-core a11y tests por página",
      "BUGFIX: session renewal enviaba solo sessionExpiresAt (rules esperaban ambos campos)",
      "BUGFIX: ConfigContext OOM dividido en 3 archivos, image-store flaky test",
      "BUGFIX: restore error mensaje, i18n clave errorDetail",
      "DEPS: TypeScript 7, jsdom 30, jest-dom 7, oxlint 1.76, @fontsource eliminados",
      "MONITORING: Sentry (prod 0.1, dev 0), Firebase Analytics, web-vitals",
      "DOCS: ARCHITECTURE.md, BROWSER_COMPAT.md, SECRETS.md, SECURITY.md, .nvmrc",
    ],
  },
  {
    version: "2.27.0",
    date: "2026-07-27",
    changes: [
      "CALIDAD: 316 typecheck errors → 0, strict flags (noUncheckedIndexedAccess, noImplicitOverride, exactOptionalPropertyTypes)",
      "CALIDAD: lint 17→0 warnings, any en source ~80→0, !important CSS 48→41",
      "TESTS: 36→127 test files, 291→1214 tests, cobertura 34.96%→75.36%",
      "TESTS: axe-core a11y, Firestore rules simulation, 7 setup-forms, 13 componentes",
      "ARQUITECTURA: hooks separados de context providers (Fast Refresh), barrel exports",
      "I18N: RSVP traducciones corregidas, errores tipográficos",
      "RSVP: rediseñado a modelo individual, menú con descripción, singular/plural attendee",
      "UI: foto novios redonda con fusión radial, nombres escalados, overflow admin corregido",
      "SEGURIDAD: CSP corregido, notAttendingCount en rules, _visits permitido",
      "RENDIMIENTO: sourcemaps condicionales, Sentry lazy load, vendor chunk splitting",
      "RENDIMIENTO: Service Worker v2, fuentes Google CDN, preconnect Firebase/Google",
      "BUGFIX: gallery/music upload crypto, RSVP i18n keys, image-store flaky test",
      "CI/CD: typecheck, JUnit, bundle size, coverage thresholds, dependabot, deploy automático",
      "DEPS: TypeScript 7, jsdom 30, jest-dom 7, oxlint 1.76",
    ],
  },
  {
    version: "2.26.0",
    date: "2026-07-26",
    changes: [
      "AUDITORÍA: ~120 puntos implementados de 250 identificados",
      "FIX: 10 altos — offline, timeout, rate limit, CSP, Sentry, CI/CD, LCP, privacidad, context split",
      "FIX: 10 medios — RTL, JSDoc, cobertura, ARIA, errores, skip-link, atajos, validación",
      "FIX: batch bajos — GalleryManager, CSS vars, z-index, import cleanup, naming, lazy loading",
      "FIX: RTL, ErrorBoundary, tests, tipos, almacenamiento, focus-visible, accesibilidad",
      "FIX: robots, schema.org, architecture.md, check-translations script",
      "FIX: WebP, tipos, validaciones, ARIA, tests, RTL, animaciones",
      "FIX: safe-areas, touch-action, print, suspenso, tests, backdrop-filter, indexedDB",
      "FIX: SW, PWA, offline, i18n, validación, seguridad, scroll, preload, tests",
      "FIX: IBAN validation, aria-live search, tests, memo checks",
      "REFACTOR: AttendanceTab columnas por persona, RSVP por asistentes individuales",
      "FIX: zoom 400% — media queries ≤480px y ≤360px",
      "FIX: Safari prefixes backdrop-filter y user-select",
      "FIX: admin bar username desde getSession()",
      "FIX: reject cookies no borra sesión",
      "TESTS: +99 tests (7 módulos, 13 componentes), coverage thresholds",
    ],
  },
  {
    version: "2.25.0",
    date: "2026-07-25",
    changes: [
      "AUDITORÍA: 50+ puntos, README, CHANGELOG actualizados",
      "FEAT: popup confirmación si hay RSVPs al cambiar menú",
      "FIX: i18n completo — offline, countdown, menús, dietas, fecha, impresión, versión",
      "FIX: attendees model — total invitados = suma de attendees.length",
      "FIX: foto novios 700px, 4:3, border-radius 1.5rem, mask-image radial",
      "FIX: botones mapa/calendario padding 2%",
      "CI: bundle size check, coverage thresholds, Sentry, dependabot",
    ],
  },
  {
    version: "2.24.0",
    date: "2026-07-24",
    changes: [
      "FIX: MAX_DURATION_SEC 30→20s (doble base64 excedía 1MB Firestore)",
      "FEAT: autoplay + loop en MusicPlayer",
      "FEAT: modal con setupToken tras crear invitación",
      "FIX: navigator.credentials.store en login (browser guarda credenciales)",
      "FIX: autoplay sincroniza estado playing con ecualizador",
      "FIX: AccessTab simplificado (sin confirmación)",
      "FIX: hero.eyebrow array→string en 85 idiomas",
    ],
  },
  {
    version: "2.23.0",
    date: "2026-07-23",
    changes: [
      "FIX: crítico — musicFile se perdía tras save (delete sin restaurar)",
      "FIX: music-player z-index 10001 (por debajo del nav-overlay 10002)",
      "FIX: envelope timing más lento y fluido (flap 1.2s, letter fade 1.2s + delay 0.5s)",
      "FIX: overflow hidden envelope",
      "FEAT: SupportTab 2 columnas + uploads unificados con estilo galería",
      "FEAT: autoplay en mobile via custom event desde envelope tap",
    ],
  },
  {
    version: "2.22.0",
    date: "2026-07-22",
    changes: [
      "FIX: MusicArrayEditor sin controles nativos (Safari AirPlay error)",
      "FIX: error handling masivo (useSetupAuth + AuthContext + traducciones)",
      "FIX: restore backup (Firestore rules + preservar sesión)",
      "FIX: CRÍTICO — sesión Firestore nunca renovada",
    ],
  },
  {
    version: "2.21.0",
    date: "2026-07-21",
    changes: [
      "FIX: 15 silent catches convertidos a toasts de error",
      "FIX: audio comprimido sonaba lento y con reverb (resampling manual incorrecto)",
      "FEAT: audio chunked (22050Hz, 60s, dividido en fragmentos de 500KB)",
      "REFACTOR: gallery+audio como subcolecciones de invitations/{token}",
      "FEAT: login valida username contra adminUsername",
    ],
  },
  {
    version: "2.20.0",
    date: "2026-07-20",
    changes: [
      "FIX: music upload redesign (audioData collection, gallery-like UI)",
      "FEAT: MusicArrayEditor en CoverSectionForm (no sección separada)",
      "FIX: auto-save debounce 3s→1.5s",
      "FIX: audio sin límite de duración (canción completa)",
      "FIX: admin bar muestra username en vez de inviteToken",
    ],
  },
  {
    version: "2.19.0",
    date: "2026-07-19",
    changes: [
      "FIX: audio upload (compressAudio), restore cleanup",
      "FIX: couple photo infinite loading + loading spinner en galería",
      "FIX: GallerySection null currentTarget.dataset error",
    ],
  },
  {
    version: "2.18.0",
    date: "2026-07-18",
    changes: [
      "FIX: críticos (location, readFileAsDataUrl, chart-utils, cascadeDelete) + altos",
      "FIX: background image 100K gate eliminado",
      "FIX: couplePhoto loading infinito corregido",
    ],
  },
  {
    version: "2.17.0",
    date: "2026-07-17",
    changes: [
      "FIX: restore backup (Firestore rules + preservar sesión)",
      "FIX: CRÍTICO sesión Firestore nunca renovada",
      "FIX: restore usa updateDoc en vez de setDoc",
      "FIX: app-scene top offset",
    ],
  },
  {
    version: "2.16.0",
    date: "2026-07-16",
    changes: [
      "I18N: +14 idiomas (99 total)",
      "FEAT: nuevo idioma Panyabí (pa)",
      "FIX: alturas contenedores (story-section, body, app-scene, footer)",
      "FIX: overflow admin panels (setup-card--wide height)",
      "FIX: solapamiento secciones admin (setup-form stretch)",
      "FIX: botones mapa/calendario padding 2%",
      "FIX: godparents text glow animado con var(--flower-accent)",
    ],
  },
  {
    version: "2.15.0",
    date: "2026-07-15",
    changes: [
      "SEO: PWA manifest, font preload, loading=lazy, título dinámico",
      "I18N: 82/82 idiomas completos, traducciones nativas 16 idiomas",
      "FIX: RTL, aria-invalid RSVP, console.warn eliminado",
      "FIX: DataTab CSS, dead props eliminados",
      "FIX: validación archivos vacíos en todos los uploads",
      "FIX: traducciones ES/EN incorrectas propagadas a 80 idiomas",
    ],
  },
  {
    version: "2.14.0",
    date: "2026-07-14",
    changes: [
      "PERF: CSS muerto eliminado, touch targets 44px, lazy modales",
      "FIX: revert lazy LegalModal/ChangelogModal (imports estáticos)",
      "REFACTOR: TokensTab y DataTab migrados a clases CSS",
      "FIX: RTL toast, aria añadido",
    ],
  },
  {
    version: "2.13.0",
    date: "2026-07-13",
    changes: [
      "PERF: bundle 9.0→6.1MB, fuentes latin-only, vendor chunk",
      "FIX: PanelTab inviteToken undefined",
      "FIX: AttendanceTab formatDate desde config",
      "FIX: RSVP responsive + input date mobile",
      "FIX: PrintPage solo mensaje+fecha+ubicación",
    ],
  },
  {
    version: "2.12.0",
    date: "2026-07-12",
    changes: [
      "FIX: eliminar SoundCloud, nuevo AudioUploadPicker con subida de ficheros",
      "FIX: AttendanceTab crash rsvpEntries/filteredEntries undefined",
      "FIX: eliminar botones Vista previa y Como invitado de /admin",
      "FIX: MusicPlayer animaciones elegantes, FAB desplazamiento",
      "FIX: NavBar sticky/fixed, PrintPage reescrita desde cero",
    ],
  },
  {
    version: "2.11.0",
    date: "2026-07-11",
    changes: [
      "FIX: sello de cera realista en solapa + fuentes más grandes",
      "FIX: nombres al borde inferior del envelope",
      "FIX: sello subido ligeramente, sombra en solapa",
      "FIX: fondo animado con profundidad radial y brillo",
    ],
  },
  {
    version: "2.10.0",
    date: "2026-07-10",
    changes: [
      "FEAT: envelope realista (papel crema, sombra, luces orbitales)",
      "FIX: scroll bloqueado mientras envelope visible",
      "TESTS: +113 tests en 9 módulos, bugfix crypto (iter count 2→3 bytes)",
      "FIX: CSP font-src data: permitido",
    ],
  },
  {
    version: "2.9.0",
    date: "2026-07-09",
    changes: [
      "FEAT: TypeScript migration",
      "FIX: security hardening, SoundCloud picker",
      "FIX: accessibility — focus visible, aria, contraste",
    ],
  },
  {
    version: "2.8.0",
    date: "2026-07-08",
    changes: [
      "REFACTOR: CSS modularizado en 15 archivos (gallery, envelope, music, a11y, lang, toast, print, admin, modals, landing, decorations)",
      "FEAT: fireflies animados (24 unidades, 6 colores, 4 trayectorias)",
      "FIX: footer siempre visible, admin bar separada",
      "FIX: z-index modales 10001 (por encima envelope 9999)",
    ],
  },
  {
    version: "2.7.0",
    date: "2026-07-07",
    changes: [
      "FEAT: envelope animado con flash blanco, texto dorado, glow orbital",
      "FEAT: dos clics — primero abre, segundo animación de salida",
      "FEAT: unificación hero con story-card, mismos estilos",
      "FIX: reglas Firestore gallery update/delete mejoradas",
      "FIX: gallery caption con fade+slide, blur→unblur 1.8s",
    ],
  },
  {
    version: "2.6.0",
    date: "2026-07-06",
    changes: [
      "FEAT: galería con 10 slots fijos, galleryData como fuente única",
      "FEAT: CRUD completo en galería con orden persistente",
      "FIX: loadGallery sin orderBy (falta índice), sort client-side",
      "FIX: descripciones cifradas, fondo gradiente en imagen",
    ],
  },
  {
    version: "2.5.0",
    date: "2026-07-05",
    changes: [
      "FEAT: nueva colección galleryData (inviteToken, position, data)",
      "FIX: RSVP form con scroll interior, overflow controlado",
      "FIX: TDZ persistOrder en GalleryArrayEditor",
    ],
  },
  {
    version: "2.4.0",
    date: "2026-07-04",
    changes: [
      "FEAT: scroll-snap CSS nativo reemplaza JS navigation",
      "FIX: body::before fijo fullscreen, app-scene bg, secciones min-height",
      "FIX: fondo elegante con glow radial por tema en body",
      "FEAT: luciérnagas animadas + glow elegante",
      "FIX: galería 10 imágenes máx, ordenada por createdAt",
    ],
  },
  {
    version: "2.3.0",
    date: "2026-07-03",
    changes: [
      "FEAT: fondos body por tema con decoraciones florales CSS",
      "FIX: showRsvp condicional a config, RsvpSection eager load",
      "FIX: isSavingRef trabado por auto-save (nunca se reseteaba)",
      "FIX: body bg Safari (remove background-attachment fixed)",
    ],
  },
  {
    version: "2.2.0",
    date: "2026-07-02",
    changes: [
      "FEAT: RSVP acompañantes/menú, animación sobre, fondos por tema",
      "FIX: sobre realista y fondos animados por tema",
      "FIX: RSVP visible con Suspense, campos nombres invitados, validaciones",
      "I18N: envelope y calendar strings, scan completo de hardcoded strings",
    ],
  },
  {
    version: "2.1.0",
    date: "2026-07-01",
    changes: [
      "FEAT: 76+ idiomas i18n (react-i18next), LanguageSwitcher",
      "FEAT: compliance GDPR/CCPA/LGPD/PIPEDA/POPIA + cookie consent + derechos ARSO",
      "FEAT: registro Art. 30 GDPR, compliance tab en superadmin",
      "FEAT: animaciones de salida en modales y popup idioma",
      "FIX: estructura namespaces i18n, dot notation final",
      "FIX: gatear localStorage/sessionStorage tras consentimiento",
    ],
  },
  {
    version: "2.36.0",
    date: "2026-07-31",
    changes: [
      "FEAT: Google Maps URL en vez de Leaflet/OSM — nuevo campo weddingMapUrl en config",
      "FEAT: DateSectionForm reescrita — input de URL con validación + iframe preview",
      "FEAT: WeddingMap simplificado — solo recibe mapUrl, sin geocodificación",
      "FEAT: DetailsSection usa weddingMapUrl directamente, sin locationMapTarget",
      "FEAT: isValidGoogleMapsUrl + convertToEmbedUrl en geo-utils",
      "CLEANUP: eliminado useMapPreview hook y map-utils (OSM tile canvas)",
      "CLEANUP: eliminado locationMapTarget/Error/Loading de UIContext",
      "CLEANUP: eliminado OSM search (searchLocations, handlePlaceChange, geocodeLocation)",
    ],
  },
  {
    version: "2.0.1",
    date: "2026-06-30",
    changes: [
      "FEAT: accesibilidad — 8 opciones (OpenDyslexic, alto contraste, escala grises, foco visible)",
      "FEAT: footer con legal, idioma, accesibilidad y versión",
      "FEAT: changelog completo desde inicio del desarrollo",
      "FIX: navbar sticky, admin-bar offset, overflow inferior",
      "FIX: CSP font-src, frame-ancestors meta, firebase getFirestore",
      "FIX: galería con progress bar real, miniaturas en tiempo real",
      "FIX: carrusel automático 1.5s, descripciones editables",
      "FEAT: superadmin — export/eliminación individual, masiva y completa",
      "FIX: sesiones migradas a activeSession en invitación",
      "FIX: XSS innerHTML → createElement",
      "FIX: footer redes sociales, copyright y copyright del programador",
    ],
  },
];
